import { Business } from "@/types";

export const demoBusiness: Business = {
  id: "1",
  slug: "kahve-duragi",
  name: "Kahve Durağı",
  tagline: "Lezzetin tam doğru adresi.",
  description:
    "El yapımı kahveler, taze sandviçler ve özel tatlılar. Her gün sevinçle hazırlanıyor, her yudumda hissediliyor.",
  logo: "☕",
  coverEmoji: "☕",
  phone: "0322 XXX XX XX",
  address: "Atatürk Cad. No:42, Çukurova / Adana",
  hours: "07:00 – 22:00",
  rating: 4.9,
  reviewCount: 1200,
  categories: [
    {
      id: "coffee",
      name: "Sıcak Kahveler",
      emoji: "☕",
      count: 12,
      gradient: "from-amber-950 to-stone-900",
    },
    {
      id: "sandwich",
      name: "Sandviç & Tost",
      emoji: "🥪",
      count: 8,
      gradient: "from-yellow-950 to-amber-900",
    },
    {
      id: "dessert",
      name: "Tatlılar",
      emoji: "🎂",
      count: 10,
      gradient: "from-rose-950 to-pink-900",
    },
    {
      id: "cold",
      name: "Soğuk İçecekler",
      emoji: "🥤",
      count: 6,
      gradient: "from-emerald-950 to-teal-900",
    },
  ],
  featuredItems: [
    {
      id: "1",
      name: "Özel Latte",
      description: "Etiyopya harmanı, el köpürtmeli süt, ev yapımı vanilyalı şurup.",
      price: 85,
      category: "coffee",
      emoji: "☕",
      badge: "Popüler",
      rating: 4.9,
      reviewCount: 218,
    },
    {
      id: "2",
      name: "New York Cheesecake",
      description: "Günlük taze pişirilen, ev yapımı.",
      price: 120,
      category: "dessert",
      emoji: "🎂",
      badge: "Özel",
      rating: 4.8,
      reviewCount: 164,
    },
    {
      id: "3",
      name: "Acai Bowl",
      description: "Granola, muz, çilek ve yaban mersini.",
      price: 145,
      category: "cold",
      emoji: "🫐",
      badge: "Yeni",
      rating: 4.7,
      reviewCount: 89,
    },
  ],
  menuItems: [
    { id: "m1", name: "Filtre Kahve", description: "Etiyopya · Orta kavrum", price: 65, category: "coffee", emoji: "☕" },
    { id: "m2", name: "Cappuccino", description: "Çift shot · İnce köpük", price: 85, category: "coffee", emoji: "🥛" },
    { id: "m3", name: "Matcha Latte", description: "Sıcak veya buzlu", price: 95, category: "cold", emoji: "🍵" },
    { id: "m4", name: "Tiramisu", description: "Ev yapımı · Günlük taze", price: 110, category: "dessert", emoji: "🍰" },
    { id: "m5", name: "Club Sandviç", description: "Tam buğday · Taze sebze", price: 150, category: "sandwich", emoji: "🥪" },
    { id: "m6", name: "Berry Smoothie", description: "Muz · Çilek · Yaban mersini", price: 105, category: "cold", emoji: "🫐" },
  ],
};
